### ISSUE TITLE
Discrepancy with endpoint log data compared to client side events w/ 3rd party widget usage

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/bq-endpoint-logger#13]
Summary of the discrepancy is in [this doc](https://docs.google.com/document/d/1NnGgclq9SYmvLKIvbonvS-SoDzO1D9XgDstsUnYgo3w/edit#heading=h.n7wpighginsg).

Once resolved, please update [this query](https://docs.google.com/document/d/1jqxPaqmy4p3_wEftp9M84RStjRXz_ag8tN0KOTz-Ifw/edit#) to use endpoint events

**Comment by tejohnso** [comment]
Confirmed closed with https://github.com/Rise-Vision/bq-endpoint-logger/pull/17

See [card](https://trello.com/c/W6p2oiEo/6436-3-defect-13-discrepancy-with-endpoint-log-data)
