### ISSUE TITLE
Discrepancy with template usage in endpoint event log data vs client side event

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/bq-endpoint-logger#14]
Details in [this doc](https://docs.google.com/document/d/1k4QHdLrMQATSHFRQQX9rCZVA1vjyRsoZBwqS02cMS64/edit).

**Comment by olegrise** [comment]
Fixed.

**Comment by olegrise** [comment]
@alanclayton just FYI, we fixed the problem that caused the discrepancy but it will take couple of days for the fix to propagate and correct data being recorded. We'll keep the issue open until then.

**Comment by stulees** [comment]
As per @alanclayton analysis, data now looking consistent from previous 2 days - https://www.screencast.com/t/udXLIAZT, closing issue.
