### ISSUE TITLE
embedReferralURL log data is not accurate

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/bq-endpoint-logger#15]
My expectation is that embedReferralURL should provide the URL fo the website that a schedule is embedded. For example, if I embed Schedule A (a.com) in Website B (b.com) then b.com should be logged as embedReferralURL.  Instead, it looks like a.com is being logged as the value for embedReferralURL.

**Comment by tejohnso** [comment]
Fixed with above correction
