### ISSUE TITLE
widget-text uptime is 100% even thought there are errors

### ISSUE THREAD

**Issue by olegrise** [Rise-Vision/bq-endpoint-logger#18]
widget-text logs error E000000055 regularly. It is strange that uptime for the widget-text is 100%.

**Comment by tejohnso** [comment]
@olegrise can you clarify where you're seeing widget-text uptime as 100% where it shouldn't be?

Here's at least one case where it is not 100%:

```
SELECT
  *
FROM
 `endpoint-event-logs.logs.dailyUptime`
WHERE
  date = "2021-04-19"
  and endpointid = "67WJXURKJM7B"
  and eventApp = "widget-text"
```

**Comment by olegrise** [comment]
@tejohnso I'm seeing it in [this query](https://console.cloud.google.com/bigquery?project=rvaserver2&ws=!1m5!1m4!1m3!1srvaserver2!2sbquxjob_35e7dfc2_178f9ade964!3sUS&j=bq:US:bquxjob_35e7dfc2_178f9ade964&page=queryresults), but I see now that it's a result of rounding. The original question came from @alanclayton. Alan, can you clarify where you're seeing widget-text uptime as 100%? 
@stulees

**Comment by alanclayton** [comment]
@olegrise my question to you was just a reality check to confirm if there is a problem. Historically, I recall having far more endpoints reporting the problem of not being able to retrieve a google font. If that is not the case and everything is working properly than this can be closed. Thanks

**Comment by tejohnso** [comment]
There are only 7 out of more than 6000 endpoints using widget-text that reported an error on the 20th, and they did not report many errors, their uptime for the day is still >95% 
So if you look at the whole week, across all endpoints, over the entire time period, the uptime is very close to 100%.  
Without the rounding, it shows as `99.99875762`

I don't think we have a problem with **bq-endpoint-logger**, or the queries. 
We may have a problem with **widget-text** not reporting errors when google font fails, but I think this issue can be closed as that would be a separate issue.

Closing for now, @olegrise or @alanclayton feel free to reopen if not in agreement.
