### ISSUE TITLE
Error: Expected HEARTBEAT parameters eventApp,eventAppVersion

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/bq-endpoint-logger#19]
The error "Error: Expected HEARTBEAT parameters eventApp,eventAppVersion" is being reported in console when this [shared schedule](https://widgets.risevision.com/viewer/?type=sharedschedule&id=a4d60774-b364-44e5-bcd5-ac645203fc5b) is opened. 

![image](https://user-images.githubusercontent.com/6854911/116166881-934c8b00-a6c4-11eb-81d6-682ac8535be4.png)

**Comment by stulees** [comment]
@alanclayton As discussed, this error was being logged from the rise-video test presentation from that schedule https://apps.risevision.com/templates/edit/68668cbf-c057-41af-8ec9-72e695e376de/?cid=4289a0f8-2c39-4f5d-9826-57c3d4c85d31 which is using a modified old example template and is problematic. Closing as its not true representation of a production template.
